### DISCUSSION TITLE
Problems with including default libraries

### DISCUSSION THREAD

**Discussion by mutasDev** [github/codeql#10868] [Q&A] [answered]
Hey fellows,

I am currently trying to build my own query-suite for my master's thesis and I'm stumbling across some errors with including the standard libraries from CodeQL.

my qlpack.yml looks as follows:

```
name: mutasdev/python-queries
defaultSuiteFile: python-all.qls
dependencies: 
  codeql/python-all: "*"
  codeql/suite-helpers: "*"
extractor: python
```

Trying to use this query suite in the analysis of a codeql DB results in the following error: 

_ERROR: Referenced pack 'codeql/python-all' not found. (CENSORED/Repositories/master-thesis/Analysis/Queries/py/qlpack.yml:1,1-1)
ERROR: Referenced pack 'codeql/suite-helpers' not found. (CENSORED/Repositories/master-thesis/Analysis/Queries/py/qlpack.yml:1,1-1)
A fatal error occurred: Could not resolve library path for CENSORED/Repositories/master-thesis/Analysis/Queries/py_

I have also tried to use the relative path to the library pack into the dependencies field, but `../../../../codeql/python-all` is not an elligible string for the path, as '..' are not allowed.

Any insights for me, on how to correctly include the library in my ql pack?
