### DISCUSSION TITLE
Running ALL queries

### DISCUSSION THREAD

**Discussion by ricardo-noyolalozano** [github/codeql#12791] [Q&A] [answered]
Howdy, I'm trying to run every single query that is in the repository. 
This is my codeql-config file that my workflow is referencing:
```
name: "CodeQL config"
packs:
    javascript:
     - codeql/javascript-queries

    csharp:
     - codeql/csharp-queries

```
Doing <language>-queries or -all does not get me all the queries in that folder. Notably I've been using the 'BaddCheckOdd.ql' as an indicator to see if it ran all of them and noticed that it never shows up in the logs. What is the pack that would give me the most extensive testing?
