### DISCUSSION TITLE
Run CodeQL analysis (javascript) on a particular sub-directory in a repo

### DISCUSSION THREAD

**Discussion by vc-lijup-nandana** [github/codeql#14320] [Q&A]
I have a repo with many microservices each will have separate CI pipeline in the same repo. I need to scan each microservices separately, which are in separate directory. 

I tried following code

```
name: 'CI - Demo Job - Bing'

on:
  workflow_dispatch:
  push:
    paths:
      - 'app1/services/microservice1'
   
jobs:
  sast:
    name: Static Application Security Testing (SAST)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code into subdirectory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all history for accurate path filtering
          path: 'app1/services/microservice1'  # Specify the directory to checkout

      # Continue with your CodeQL setup and analysis steps
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript
          queries: security-extended,security-and-quality

      - name: Javascript Autobuild
        uses: github/codeql-action/autobuild@v2 

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:javascript"
```
          
But this is scanning the entire repo and services not only limited to microservice1
