### DISCUSSION TITLE
[Go] No results when using MaD vs Query to model sink for function

### DISCUSSION THREAD

**Discussion by rh-tguittet** [github/codeql#16494] [Q&A]
Hi, I am trying to model the following (set of) function(s) using Model-as-Data: https://pkg.go.dev/github.com/openshift/library-go@v0.0.0-20240513090140-e22d25af5587/pkg/operator/resource/resourceapply#ApplyConfigMap

Here's my mad file: `ext/github.com.openshift.library-go.pkg.operator.resource.resourceapply.yml`
```yaml
extensions:
  - addsTo:
      pack: codeql/go-all
      extensible: sinkModel
    data:
      # string package, string type, boolean subtypes, string name, string signature, string ext, string input, string kind, string provenance
      - ["github.com/openshift/library-go/pkg/operator/resource/resourceapply", "", True, "ApplyConfigMap", "", "", "Argument[3]", "special", "manual"]
```

My query is as follows:
```codeql
import go
import DataFlow
import semmle.go.dataflow.ExternalFlow

/**
 * The following works and returns the expected result.
 */
// from DataFlow::Node node, Function f
// where f.getQualifiedName() = "github.com/openshift/library-go/pkg/operator/resource/resourceapply.ApplyConfigMap" and node = f.getACall().getArgument(3)
// select node, f, f.getQualifiedName()

/**
 * This does not return anything.
 */
from DataFlow::Node node
where sinkNode(node, "special")
select node
```

This is happening in a QL pack with other MaD. The other MaD work, I can confirm that they do by replacing `"special"` by `_` and viewing the expected results from those MaD.

CodeQL version info:
```
CodeQL extension version: 1.13.0 
CodeQL CLI version: 2.16.4 
Platform: linux x64
```

Something must be amiss but I can't work out what. (I also don't know how to _debug_ what's happening here.) What am I missing?

Thanks in advance!
