### DISCUSSION TITLE
CodeQL scan is successful but alerts are not coming up in Github UI

### DISCUSSION THREAD

**Discussion by AishwaryaGumastha** [github/codeql#16905] [Q&A]
Hi Team,
I have being trying to perform codeQL scan on one of my repository where i added few vulnerabilities scan is running successfully, but when i check in github there are no alerts. I have being using github actions to perform the scan but when i perform the scan using codeql cli i am able to see the alerts in github. Can any please help what i am missing .
Here is my actions code:

```
name: "CodeQL"
on:
  push:
    branches: [ "dev" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "dev" ]
  schedule:
    - cron: '* * * * 1' # Runs every Monday at 00:00 UTC

jobs:
  analyze:
    name: Analyze
    runs-on: code-scanning
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java','kotlin' ] # Add or remove languages as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
      
    - name: Set NODE_TLS_REJECT_UNAUTHORIZED
      run: |
        echo "NODE_TLS_REJECT_UNAUTHORIZED=0" >> $GITHUB_ENV

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
          output: ./results

    - name: Upload CodeQL Database
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: codeql-database
        path: ${{ runner.temp }}/codeql_databases
        
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
          sarif_file: results/java.sarif
          category: codeQL-scan
```
