### DISCUSSION TITLE
自定义安全流程配置 workflows的 codeql.yml文件时，如何配置 可以加载官网CWE的ql规则文件级别是  * @precision low的

### DISCUSSION THREAD

**Discussion by Yangxl88** [github/codeql#17994] [Q&A]
![image](https://github.com/user-attachments/assets/a912e8f0-d8d3-4f42-b4eb-7c014ebe3387)
![image](https://github.com/user-attachments/assets/da2d7b0e-52f1-4e72-85da-b1158763fa10)
![image](https://github.com/user-attachments/assets/dc6c1653-3372-45c7-8487-dac8f44fbfa9)
期待答复，谢谢

**Comment by smowton** [comment]
Since it isn't included in a default query suite, try adding it directly to your codeql-init action's options:

```yaml
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        packs: codeql/java-queries:Security/CWE/CWE-020/UntrustedDataToExternalAPI.ql
```

Note that if you're using a matrix build for multiple languages, you might need to set this in the matrix specification and use this instead, similar to how matrix builds usually treat the `languages` option:

```yaml
      with:
        packs: ${{ matrix.packs }}
```
