### DISCUSSION TITLE
Need help to create a model pack for go

### DISCUSSION THREAD

**Discussion by hugo-syn** [github/codeql#18555] [Q&A] [answered]
I have this go function: 

```go
func (s *Server) ListTriggers(ctx context.Context, q *notification.TriggersListRequest) (*notification.TriggerList, error) {
	[...]
}
```

You can find it here: https://github.com/argoproj/argo-cd/blob/v2.13.3/server/notification/notification.go#L25

I want to add the `q` parameter as an additional source using the codeql threat model feature. I have the following `ext.yml` file:
```yaml
extensions:
  - addsTo:
      pack: codeql/go-all
      extensible: sourceModel
    data:
      - ["github.com/argoproj/argo-cd/v2/server/notification", "", True, "ListTriggers", "", "", "Argument[1]", "remote", "manual" ]
  - addsTo:
      pack: codeql/go-all
      extensible: sinkModel
    data: []
  - addsTo:
      pack: codeql/go-all
      extensible: summaryModel
    data: []

```

I'm running the following query to check if I have additional entries in the output with the model:
```ql
 import semmle.go.security.FlowSources

 from RemoteFlowSource::Range source
 where not source.getFile().getRelativePath().matches("%/test/%")
 select source, ""
```

But I get the same number of result with and without my model pack. So is my model pack correct ? How can I test if it's really adding sources ? 

Here is my command line:
```sh
$ codeql database analyze /../argo-cd-v2.13.3 --format=sarif-latest --output=/../sarif-remote-flow-sources.sarif --additional-packs /.../argocd-cd-ext/ --additional-packs /../argocd-cd/ --model-packs synacktiv/argocd-cd-ext synacktiv/argocd-cd:query.ql --rerun
```
