### DISCUSSION TITLE
[csharp] need help with taint propagation

### DISCUSSION THREAD

**Discussion by Hug0Vincent** [github/codeql#19911] [Q&A] [answered]
Hi, I don't understand why my taint is not propagating. I have 3 test cases that look similar, but it only works for one. Here is my C# code:

```csharp
protected FullyInstrumentedType(SerializationInfo info, StreamingContext context)
        {
            Console.WriteLine("Deserialization constructor");
            Data = info.GetString("Data");

            //1
            BinaryFormatter binaryFormatter = new BinaryFormatter();
            using (MemoryStream memoryStream = new MemoryStream(Convert.FromBase64String(this.Data)))
            {
                binaryFormatter.Deserialize(memoryStream);
            }

            //2
            byte[] a = Convert.FromBase64String(this.Data);
            MemoryStream stream = null;
            stream =  new MemoryStream(a);
            (new BinaryFormatter()).Deserialize(stream);

            //3
            byte[] b = Encoding.UTF8.GetBytes(this.Data);
            MemoryStream ms = null;
            ms = new MemoryStream(b);
            (new BinaryFormatter()).Deserialize(ms);
```

In the first scenario, the taint halts at the `FromBase64String `call, whereas in the third scenario, it persists until the `Deserialize `call, which aligns with my expectations. This observation was confirmed through a partial dataflow query:

![Screenshot 2025-06-28 132622](https://github.com/user-attachments/assets/f9c4a903-59d4-4c16-bbe6-b820eb0f0af7)
![Screenshot 2025-06-28 133221](https://github.com/user-attachments/assets/55441dcd-6201-4004-a78c-bd935b996edd)

```ql
/**
 * @name Forward Partial Dataflow
 * @description Forward Partial Dataflow
 * @kind path-problem
 * @precision low
 * @problem.severity error
 * @id githubsecuritylab/forward-partial-dataflow
 * @tags template
 */

import csharp
import semmle.code.csharp.dataflow.TaintTracking
import semmle.code.csharp.serialization.Serialization
import PartialFlow::PartialPathGraph
import libs.Source

private module MyConfig implements DataFlow::ConfigSig {
  
  predicate isSource(DataFlow::Node mysrc) {
      mysrc.asParameter().getCallable() instanceof SerializationConstructor and
      ( mysrc.asParameter().getCallable().hasName("ClaimsPrincipal") or 
        mysrc.asParameter().getCallable().hasName("FullyInstrumentedType")
      )
    
  }

  predicate isAdditionalFlowStep(DataFlow::Node node1, DataFlow::Node node2) {
    any(SerializationInfoGetTaintStep s).step(node1, node2) 
  }

  predicate isSink(DataFlow::Node sink) { none() }
}

/**
 * We want to propagate output of SerializationInfo:
 * 
 *  Data = info.GetString("Data");
 */
class SerializationInfoGetTaintStep extends GadgetAdditionalTaintStep {
  override predicate step(DataFlow::Node fromNode, DataFlow::Node toNode) {
    exists(MethodCall mc, Method m |
      mc.getTarget() = m and
      m.getName().matches("Get%") and
      m.getDeclaringType().hasFullyQualifiedName("System.Runtime.Serialization", "SerializationInfo") and

      // Taint flows from the qualifier (info) to the call result
      fromNode.asExpr() = mc.getQualifier() and
      toNode.asExpr() = mc
    )
  }
}

private module MyFlow = TaintTracking::Global<MyConfig>; // or DataFlow::Global<..>

int explorationLimit() { result = 10 }

private module PartialFlow = MyFlow::FlowExplorationFwd<explorationLimit/0>;

from PartialFlow::PartialPathNode source, PartialFlow::PartialPathNode sink
where PartialFlow::partialFlow(source, sink, _)
select sink.getNode(), source, sink, "This node receives taint from $@.", source.getNode(),
  "this source"
```

Based on [this](https://github.com/github/codeql/blob/38fdf7eea0bdaf2811a58f71a5f2a6b939568521/csharp/ql/lib/ext/System.model.yml#L43)  it should propagate the taint. What am I missing here ? 

Thank you.

**Comment by Hug0Vincent** [comment]
Using the same query on a different Codeql database yield the same problem on another method:

![Screenshot 2025-06-29 112009](https://github.com/user-attachments/assets/25920106-0d8e-40c3-9cef-0d18409feaae)

And again there is a summary step for this method [here](https://github.com/github/codeql/blob/38fdf7eea0bdaf2811a58f71a5f2a6b939568521/csharp/ql/lib/ext/generated/System.Xml.model.yml#L59). So the problem might be somewhere else, I don't understand

**Reply by Hug0Vincent** [reply]
Oh no [here ](https://github.com/github/codeql/blob/38fdf7eea0bdaf2811a58f71a5f2a6b939568521/csharp/ql/lib/ext/generated/System.Xml.model.yml#L616) there is a neutral step for this method, I don't understand why there is a difference between the 2 method signatures.

**Reply by michaelnebel** [reply]
There is probably not a difference - but our model generator has not been able to detect flow for the `CreateBinaryReader` for all overloads (these are automatically generated). Which overload are you using in the screenshot to the left?

**Reply by Hug0Vincent** [reply]
It's this [one](https://github.com/github/codeql/blob/38fdf7eea0bdaf2811a58f71a5f2a6b939568521/csharp/ql/lib/ext/generated/System.Xml.model.yml#L616) and it's in the `neutralModel` part, if you want the MS doc it's [here](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xmldictionaryreader.createbinaryreader?view=net-9.0#system-xml-xmldictionaryreader-createbinaryreader(system-byte()-system-int32-system-int32-system-xml-ixmldictionary-system-xml-xmldictionaryreaderquotas-system-xml-xmlbinaryreadersession-system-xml-onxmldictionaryreaderclose)).

**Comment by Hug0Vincent** [comment]
I think that in my first example the difference is in the way the return value is tainted. For `GetBytes` it's the `ReturnValue` ([here](https://github.com/github/codeql/blob/38fdf7eea0bdaf2811a58f71a5f2a6b939568521/csharp/ql/lib/ext/System.Text.model.yml#L11)) and for `FromBase64String` ([here](https://github.com/github/codeql/blob/38fdf7eea0bdaf2811a58f71a5f2a6b939568521/csharp/ql/lib/ext/System.model.yml#L43)) it's `ReturnValue.Element`. What's the difference ?

**Reply by Hug0Vincent** [reply]
I have another example here where the taint stop with the same query:

![Screenshot 2025-06-30 145652](https://github.com/user-attachments/assets/f2453caa-f17b-4930-a39b-994e8fb9bfb6)

I don't know which is responsible [here](https://github.com/github/codeql/blob/38fdf7eea0bdaf2811a58f71a5f2a6b939568521/csharp/ql/lib/ext/generated/System.Runtime.Serialization.model.yml#L52C1-L53C1) or [here](https://github.com/github/codeql/blob/38fdf7eea0bdaf2811a58f71a5f2a6b939568521/csharp/ql/lib/ext/generated/System.Runtime.Serialization.model.yml#L60). I'm probably missing something and hope someone can explain it, thank you :)

**Reply by michaelnebel** [reply]
The issue is that the models for the methods can't be "chained" correctly.
As it is now `GetBytes` taints the return object (the array) and `MemoryStream(byte[])` propagates taint from the array to the object.
However, the summary for `FromBase64String` only states that the elements of the return value are tainted (so this can't be correctly chained with the summary for `MemoryStream(byte[])`).

**Reply by michaelnebel** [reply]
I overlooked one of your questions: 
It appears that the `isAdditionalFlowStep` predicate in the provided example also covers the `info.GetEnumerator()`, which explains why taint propagates just fine to `enumerator`. However, this doesn’t work well with the generated models for these types. Instead of adding the query/example specific additional flow steps, we might be able to introduce some models for these types that cover this case (and which are reasonable for general use).

**Reply by Hug0Vincent** [reply]
Yes I initially added this for the `GetString` method because it was not propagating the taint as explained in this discussion: https://github.com/github/codeql/discussions/18647  (it might be the same problem actually)

I didn't realize that it would also be applied to `GetEnumerator` ! It would be nice to have a model for this

**Comment by michaelnebel** [comment, marked as answer]
Thank you very much for reporting this.
I suspect at least for some of the cases there are some issues with the Models as Data modelling of the library methods.
With the current modelling we have
```
Convert.FromBase64String(string) : Argument[0] -> ReturnValue.Element
Encoding.GetBytes(string) : Argument[0] -> ReturnValue
MemoryStream.MemoryStream(byte[]) : Argument[0] -> Argument[this]
```
It looks like the model for `MemoryStream.MemoryStream(byte[])` is incorrect (it should be `Argument[0].Element -> Argument[this]` - this is also the case for the other overloads of the constructor). Also the model for `Encoding.GetBytes` looks incorrect as taint is propagated from the argument to the return value (instead of the elements of the return value).

I will look into this.

**Reply by Hug0Vincent** [reply]
Thank you for your answer, let me know if I can provide additional information

**Comment by michaelnebel** [comment]
@Hug0Vincent : Will see if I can fix at least some of the modelling and get back to you.

**Reply by Hug0Vincent** [reply]
Thank you so much for looking into this :)

**Comment by michaelnebel** [comment]
Related PR https://github.com/github/codeql/pull/19940

**Reply by Hug0Vincent** [reply]
Thank you so much it works now for my case ! I haven't tested the new models for `System.Runtime.Serialization` since I want to catch all the `Get*` calls.

If I encounter similar issues with other functions, what is the best way to report them ?

**Reply by owen-mc** [reply]
Opening an issue here is the best way of reporting the issue. Or, if you feel able to fix it yourself, you are always welcome to open a pull request.

**Comment by michaelnebel** [comment]
The related PR #19940 has been merged.

**Comment by Hug0Vincent** [comment]
Hi @michaelnebel I've reopened the issue because I found a new variant of this bug this time with the `StringReader` class [here ](https://github.com/github/codeql/blob/d64a9368d2a83bb45c2531ad21db721f4ccb1b1e/csharp/ql/lib/ext/generated/System.Xml.model.yml#L403) there are `summaryModel `for some constructors, but others are defined in `neutralModel` ([here](https://github.com/github/codeql/blob/d64a9368d2a83bb45c2531ad21db721f4ccb1b1e/csharp/ql/lib/ext/generated/System.Xml.model.yml#L926)). A false positive of one of my query lead me find this one. In my case I have this pattern and I would assume that the result would be tainted, but that's not the case:

```c#
new XmlTextReader(new StringReader(taintedString))
```  

As a workaround I've added this line in the yaml file and it works:
```yml
- ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.IO.TextReader)", "", "Argument[0]", "Argument[this]", "taint", "dfc-generated"]
```

I'm unsure if certain constructors should be filtered out. 

How are those generated model packs created?

**Reply by owen-mc** [reply]
Thank you for reporting this. @michaelnebel is on holiday for the next three weeks. He will reply when he gets back. From a quick glance it seems likely that more of the constructors need a non-`neutral` model. The generated model packs are known to be imprecise at times.

**Reply by michaelnebel** [reply]
Just acknowledging that I have seen the ping, but I haven't had time to look into yet.

**Reply by michaelnebel** [reply]
@Hug0Vincent : I need a bit more context. Could you share the query and some example code?
Did you add more models than
```
- ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.IO.TextReader)", "", "Argument[0]", "Argument[this]", "taint", "dfc-generated"]
```
For this model to have an effect I would expect that some other methods needed to be modelled as well (some that reads from `Argument[this]`).

**Reply by Hug0Vincent** [reply]
@michaelnebel , I've added this without thinking too much:

```yaml
extensions:
  - addsTo:
      pack: codeql/csharp-all
      extensible: summaryModel
    data:
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.IO.Stream,System.Xml.XmlNodeType,System.Xml.XmlParserContext)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.String)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.String,System.IO.Stream,System.Xml.XmlNameTable)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.String,System.IO.TextReader,System.Xml.XmlNameTable)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.String,System.Xml.XmlNameTable)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.String,System.Xml.XmlNodeType,System.Xml.XmlParserContext)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.IO.Stream)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.IO.Stream,System.Xml.XmlNameTable)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.IO.TextReader)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.IO.TextReader,System.Xml.XmlNameTable)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.String,System.IO.Stream)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlTextReader", False, "XmlTextReader", "(System.String,System.IO.TextReader)", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      - ["System.Xml", "XmlDictionaryReader", True, "ReadContentAsBase64", "()",  "", "Argument[this]", "ReturnValue", "taint", "manual"]
```

Here is a code example from my codebase:

```c#
protected DataSet(SerializationInfo info, StreamingContext context, bool ConstructSchema)
			: this()
{
	SerializationFormat serializationFormat = SerializationFormat.Xml;
	SchemaSerializationMode schemaSerializationMode = SchemaSerializationMode.IncludeSchema;
	SerializationInfoEnumerator enumerator = info.GetEnumerator();
	while (enumerator.MoveNext())
	{
		string name = enumerator.Name;
		if (!(name == "DataSet.RemotingFormat"))
		{
			if (name == "SchemaSerializationMode.DataSet")
			{
				schemaSerializationMode = (SchemaSerializationMode)enumerator.Value;
			}
		}
		else
		{
			serializationFormat = (SerializationFormat)enumerator.Value;
		}
	}
	if (schemaSerializationMode == SchemaSerializationMode.ExcludeSchema)
	{
		this.InitializeDerivedDataSet();
	}
	if (serializationFormat == SerializationFormat.Xml && !ConstructSchema)
	{
		return;
	}
	this.DeserializeDataSet(info, context, serializationFormat, schemaSerializationMode);
}

internal void DeserializeDataSet(SerializationInfo info, StreamingContext context, SerializationFormat remotingFormat, SchemaSerializationMode schemaSerializationMode)
{
	this.DeserializeDataSetSchema(info, context, remotingFormat, schemaSerializationMode);
	this.DeserializeDataSetData(info, context, remotingFormat);
}

private void DeserializeDataSetSchema(SerializationInfo info, StreamingContext context, SerializationFormat remotingFormat, SchemaSerializationMode schemaSerializationMode)
{
	if (remotingFormat == SerializationFormat.Xml)
	{
		string text = (string)info.GetValue("XmlSchema", typeof(string));
		if (text != null)
		{
			this.ReadXmlSchema(new XmlTextReader(new StringReader(text)), true);
		}
		return;
	}
	// ...
}
```

The query that I use is the one in the original question [here](https://github.com/github/codeql/discussions/19911#discussion-8507357).

You can just change the source:
```ql
predicate isSource(DataFlow::Node mysrc) {
	mysrc.asParameter().getCallable() instanceof SerializationConstructor and
	( mysrc.asParameter().getCallable().hasName("DataSet")
	)

}
```

I want to track `info` from the deserialization constructor:
```
DataSet
	DeserializeDataSet
		DeserializeDataSetSchema
			ReadXmlSchema
```

Where `ReadXmlSchema` takes a `XmlTextReader` as a parameter. Without the additional `summaryModel` the propagation stops.

**Reply by michaelnebel** [reply]
I suppose you have some further modelling for `ReadXmlSchema` or maybe that is a sink in your query?
It looks like we could benefit from doing some proper manual modelling of `XmlReader` including the sub-classes `XmlTextReader` and `XmlDictionaryReader`.

**Reply by Hug0Vincent** [reply]
My sink is deeper after ReadXmlSchema but I couldn't find it and with partial dataflow I noticed that it stopped here without the modeling modification.

That would be nice indeed can I help in some ways ?

**Reply by michaelnebel** [reply]
Opening a PR for the modelling here: https://github.com/github/codeql/pull/20290

I suppose the `ReadXmlSchema` is declared in the codebase you are analyzing? Otherwise, the partial flow might stop here as well.
You are more than welcome to contribute to the modelling of APIs when you discover that models are missing/not working - we would be very happy to get such contributions! 😄

**Reply by Hug0Vincent** [reply]
Yes exactly the function is from my codebase.

Perfect that's a nice example, I have 2 questions:

1. what's the difference between the tags: manual/df-manual/dfc-manual ?
2. How to build the expected test cases ?

Did you manually review all of the functions and do you use the vscode extension for modeling ?

**Reply by michaelnebel** [reply]
- The model provenance information `manual`, `df-manual`, `dfc-manual`, `df-generated` and `dfc-generated`: `manual` means a model that we came up with, `df-manual`/`dfc-manual` is a model that was generated by our model generator (`df` means by our heuristic model generation and `dfc` means by our content based model generation) but that we have manually "inspected" (reviewed) and thus "promoted" to a manual model (that is, models that already existed but had provenance `df-generated` or `dfc-generated`). This means that whatever models you provide will be "manual". Also, it is important to note that there is a difference in semantics for `manual` and `generated` models: `generated` models are ONLY applied in case there is no source code available for the callable (the logic is slightly more complicated - but this is the gist of it), whereas `manual` models are always applied - even if the source code is available.
- `FlowSummaries*.expected` files can be updated by running `codeql test run csharp/ql/test/library-tests/dataflow/library/ --learn` in the CodeQL clone.
- I manually reviewed all the functions and didn't use the VS Code extension. I think that the extension is most suitable when you are trying to model the codebase in your current workspace.

**Reply by Hug0Vincent** [reply]
Ok thank you so much, now I don't have any excuse, next time I'll open a PR. thank you again for all the help it's always nice to ask a question here :)

For the model generation you then fill all the parameter and types by hand ?

**Reply by michaelnebel** [reply]
For these cases there were neutral models for most of the methods (they have the right signatures) - I just copied those and provided the correct input/output columns (and the other minor remaining). It is a bit cumbersome, but at least it is easier compared to when we had to write QL for such things. 😄

**Comment by Hug0Vincent** [comment]
I have one new [here](https://github.com/github/codeql/blob/d64a9368d2a83bb45c2531ad21db721f4ccb1b1e/csharp/ql/lib/ext/generated/System.Xml.model.yml#L667) also, fixed with this:

```yaml
- ["System.Xml", "XmlDictionaryReader", True, "ReadContentAsBase64", "()",  "", "Argument[this]", "ReturnValue", "taint", "manual"]
```

Some other `Read*` might need to be added as well

**Reply by michaelnebel** [reply]
This should also be covered by https://github.com/github/codeql/pull/20290

**Comment by michaelnebel** [comment]
@Hug0Vincent : If you experience more gaps in the modelling - feel free to make a PR or open another issue with a request. The turnaround time is typically faster, if you open a PR 😄

**Reply by Hug0Vincent** [reply]
Hey @michaelnebel I'm trying to play with the sinkModel but there is something that I don't understand, I have this model:

```yaml
extensions:
  - addsTo:
      pack: codeql/csharp-all
      extensible: sinkModel
    data:
      - ["System", "Type", True, "GetMethod", "(System.String)", "", "Argument[0]", "gadget-sink", "manual"]
      - ["System.Reflection", "MethodBase", True, "Invoke", "(System.Object,System.Object[])", "", "Argument[0]", "gadget-sink", "manual"]
```

But it can't find the call to the ``Invoke`` method:

<img width="1101" height="890" alt="Screenshot 2025-08-30 072705" src="https://github.com/user-attachments/assets/ffab274e-5793-4d7f-b0ae-fd974e16aef4" />


What I'm I missing ? Since [MethodInfo](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo?view=netframework-1.1) extends ``MethodBase`` should my model also catch the call `MethodInfo.Invoke` ?

According to the [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.methodinfo?view=netframework-1.1) the third parameter is ``subtypes`` but I'm not sure if it's for overriden methods or all subtypes. 

Here is my code and my query:

```ql
/**
 * @id synacktiv/csharp/test
 * @description test
 * @name test
 * @kind table
 * @tags audit
 */

import csharp
private import semmle.code.csharp.security.dataflow.flowsinks.FlowSinks
private import semmle.code.csharp.dataflow.internal.ExternalFlow

abstract class Sink extends ApiSinkExprNode { }

private class ExternalGadgetSink extends Sink {
  ExternalGadgetSink() { sinkNode(this, "gadget-sink") }
  

}

from ExternalGadgetSink s
select s
```

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            BasePoc.BasePocPoc();
        }

        public static void Test()
        {
            // 1. Create an instance of the class
            MyClass myObject = new MyClass();

            // 2. Get the Type object
            Type type = typeof(MyClass);

            // 3. Get the MethodInfo object for the method you want to call
            MethodInfo methodInfo = type.GetMethod("SayHello");
            MethodBase methodInfo2 = type.GetMethod("SayHello");

            if (methodInfo != null)
            {
                // 4. Call the method using MethodInfo.Invoke
                methodInfo.Invoke(myObject, new object[] { "Alice" });
                methodInfo2.Invoke(myObject, new object[] { "Alice" });
            }
            else
            {
                Console.WriteLine("Method not found.");
            }
        }
    }

    public class MyClass
    {
        public void SayHello(string name)
        {
            Console.WriteLine($"Hello, {name}!");
        }
    }
}

```

Let me know if I'm asking too many questions
