### DISCUSSION TITLE
Database Error - GitHub Actions

### DISCUSSION THREAD

**Discussion by ArielSAdamsNASA** [github/codeql#6778] [Q&A] [answered]
When running CodeQL GitHub Actions with JPL queries in the configuration .yml file, there is an error "The database may be too new for the QL libraries the query is using; try upgrading them." This error occurs for JPL_C/LOC-2/Rule 07/ThreadSafety.ql. Thank you!

Error:
```
Optimizing /home/runner/work/_temp/github/codeql/main/cpp/ql/src/JPL_C/LOC-2/Rule 07/ThreadSafety.ql.
  Compiling upgrade for /home/runner/work/_temp/github/codeql/main/cpp/ql/src/JPL_C/LOC-2/Rule 07/ThreadSafety.ql
  A fatal error occurred: The CodeQL database at ../../_temp/codeql_databases/cpp
  is not compatible with the QL library ../../_temp/github/codeql/main/cpp/ql/src/JPL_C/LOC-2/Rule 07/ThreadSafety.ql uses.
  The database may be too new for the QL libraries the query is using; try upgrading them.
  Alternatively, running 'codeql database upgrade ../../_temp/codeql_databases/cpp' with an appropriate --search-path option might help.
```

Configuration .yml file:
```
name: "CodeQL Coding Standard Configuration File"

disable-default-queries: true

queries:
  - name: JPL Rules
    uses: github/codeql/cpp/ql/src/JPL_C@main
```

Workflow:
```
name: "CodeQL Analysis"

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Build, Test, and Run \\[OMIT_DEPRECATED = true\\]"]
    types:
      - completed
    branches: 
      - '**'
env:
  SIMULATION: native
  ENABLE_UNIT_TESTS: true
  OMIT_DEPRECATED: true
  BUILDTYPE: release


jobs:
  #Checks for duplicate actions. Skips push actions if there is a matching or duplicate pull-request action. 
  check-for-duplicates:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: 'same_content'
          skip_after_successful_duplicate: 'true'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

      
  CodeQL-Security-Build:
    #Continue if check-for-duplicates found no duplicates. Always runs for pull-requests.
    needs: check-for-duplicates
    if: ${{ needs.check-for-duplicates.outputs.should_skip != 'true' }}
    runs-on: ubuntu-18.04
    timeout-minutes: 15

    steps:
      # Checks out a copy of your repository
      - name: Checkout code
        if: ${{ !steps.skip-workflow.outputs.skip }}
        uses: actions/checkout@v2
        with:
          repository: nasa/cFS
          submodules: true

      - name: Check versions
        if: ${{ !steps.skip-workflow.outputs.skip }}
        run: |
           git log -1 --pretty=oneline
           git submodule
      - name: Initialize CodeQL
        if: ${{ !steps.skip-workflow.outputs.skip }}
        uses: github/codeql-action/init@v1
        with:
          languages: c
          config-file: ./.github/codeql/codeql-security.yml

      # Setup the build system
      - name: Copy sample_defs
        if: ${{ !steps.skip-workflow.outputs.skip }}
        run: |
          cp ./cfe/cmake/Makefile.sample Makefile
          cp -r ./cfe/cmake/sample_defs sample_defs
      # Setup the build system
      - name: Make Install
        if: ${{ !steps.skip-workflow.outputs.skip }}
        run: make

      # Run CodeQL
      - name: Perform CodeQL Analysis
        if: ${{ !steps.skip-workflow.outputs.skip }}
        uses: github/codeql-action/analyze@v1

  CodeQL-Coding-Standard-Build:
    #Continue if check-for-duplicates found no duplicates. Always runs for pull-requests.
    needs: check-for-duplicates
    if: ${{ needs.check-for-duplicates.outputs.should_skip != 'true' }}
    runs-on: ubuntu-18.04
    timeout-minutes: 15

    steps:
      # Checks out a copy of your repository
      - name: Checkout code
        if: ${{ !steps.skip-workflow.outputs.skip }}
        uses: actions/checkout@v2
        with:
          repository: nasa/cFS
          submodules: true

      - name: Check versions
        if: ${{ !steps.skip-workflow.outputs.skip }}
        run: |
           git log -1 --pretty=oneline
           git submodule
      - name: Checkout codeql code      
        if: ${{ !steps.skip-workflow.outputs.skip }}
        uses: actions/checkout@v2
        with:
          repository: github/codeql 
          submodules: true 
          path: codeql

      - name: Initialize CodeQL
        if: ${{ !steps.skip-workflow.outputs.skip }}
        uses: github/codeql-action/init@v1
        with:
          languages: c
          config-file: ./.github/codeql/codeql-coding-standard.yml

      # Setup the build system
      - name: Copy sample_defs
        if: ${{ !steps.skip-workflow.outputs.skip }}
        run: |
          cp ./cfe/cmake/Makefile.sample Makefile
          cp -r ./cfe/cmake/sample_defs sample_defs
 
      # Setup the build system
      - name: Make Install
        if: ${{ !steps.skip-workflow.outputs.skip }}
        run: make

      # Run CodeQL
      - name: Perform CodeQL Analysis
        if: ${{ !steps.skip-workflow.outputs.skip }}
        uses: github/codeql-action/analyze@v1
        
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - name: Fail workflow
        run: exit 1
```
