### DISCUSSION TITLE
Run CodeQL analysis on a particular sub-directory in monorepo

### DISCUSSION THREAD

**Discussion by amalay** [github/codeql#9844] [Q&A]
Hi Guys, I have monorepo and it contains multiple services written on multiple languages and separated by sub-directory. I want to run codeQL analysis on sub-directory level only. And it is working perfectly for JavaScript, TypeScript, Python sub-directories using paths/paths-ignore in codeql-config.yml file as mentioned in GitHub doc. But the same is not working for go language sub-directory. For go lang, it is start scanning all the repository's folders instead of specific go folder. Is there any limitation with go lang? or something different need to be done for go lang?

**Below is my workflow:**
```yaml
name: Lib - Scanning CodeQL

on:
  workflow_call:
    inputs:
      WORKING_DIRECTORY:
        required: true
        type: string
        description: "Working directory of the project"
      SCRIPTING_LANGUAGES:
        required: true
        type: string
        description: "Scripting languages used in the project"

jobs:
  codeql_analysis:
    name: CodeQL
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.WORKING_DIRECTORY }}

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:          
          config-file: ${{ inputs.WORKING_DIRECTORY }}/codeql-config.yml
          languages: ${{ inputs.SCRIPTING_LANGUAGES }}          
          
      # Autobuild attempts to build any compiled languages (C/C++, C#, or Java). If this step fails, then you should remove it and run the build manually.
      - name: Autobuild
        id: autobuild
        uses: github/codeql-action/autobuild@v2
        continue-on-error: true

      # If the Autobuild fails above, then build it manually.
      - if: steps.autobuild.outcome == 'failure'
        name: Manual Build
        run: |
          make bootstrap
          make release      

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
```

**My codeql config file:**
```yaml
name: 'CodeQL Config File'

paths:
  - go-hello-world-preview-app/app

paths-ignore:
  - brightskies-preview-app
  - brightskies-reporting-app
  - mdr-ds-preview-app
  - mdr-ds-static-web-app
  - mdr-preview-app
  - sirion
  - soc-preview-app
  - '**/*.yaml'
  - '**/*.yml'
  - '*.yaml'
  - '*.yml'
```
