### ISSUE TITLE
Fatal error when specifying a default pack with an `apply` file

### ISSUE THREAD

**Issue by colindembovsky** [github/codeql#10185]
I am trying to customize the selectors for scanning. Here is the Action for the init step:

```yml
- name: Initialize CodeQL Scanning
  uses: github/codeql-action/init@v2
  with:
    languages: java
    config-file: ./.github/codeql/low-precision-config.yml
```

Here is the config file:

```yml
name: "Custom CodeQL Config"
disable-default-queries: true
queries:
- uses: ./.github/codeql/low-precision-queries.qls
```

Here is the `.qls` file:

```yml
- description: Include low precision queries
- qlpack: codeql/java-queries
- apply: low-precision-selectors.yml
  from: ./github/codeql
```

With this custom selectors file for the apply, the build always fails with this error:

```
Languages from configuration: ["java"]
  /opt/hostedtoolcache/CodeQL/0.0.0-20220811/x64/codeql/codeql resolve queries /home/runner/work/colind-bookstore-v22/colind-bookstore-v22/.github/codeql/low-precision-queries.qls --format=bylanguage --additional-packs /home/runner/work/colind-bookstore-v22/colind-bookstore-v22
  Recording pack reference codeql/java-queries at /opt/hostedtoolcache/CodeQL/0.0.0-20220811/x64/codeql/qlpacks/codeql/java-queries/0.3.2.
  Recording pack reference codeql/suite-helpers at /opt/hostedtoolcache/CodeQL/0.0.0-20220811/x64/codeql/qlpacks/codeql/java-queries/0.3.2/.codeql/libraries/codeql/suite-helpers/0.2.0.
  Oops! A fatal internal error occurred.
  java.util.NoSuchElementException: No value present
  	at java.base/java.util.Optional.get(Unknown Source)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand.locatePackInner(ResolveQueriesCommand.java:1015)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand.access$1200(ResolveQueriesCommand.java:85)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand$SuiteExpansionContext.locatePack(ResolveQueriesCommand.java:807)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand$SuiteExpansionContext.namedFile(ResolveQueriesCommand.java:774)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand$SuiteExpansionContext.execute(ResolveQueriesCommand.java:645)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand$SuiteExpansionContext.execute(ResolveQueriesCommand.java:525)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand.expandInstructions(ResolveQueriesCommand.java:479)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand.expandSuite(ResolveQueriesCommand.java:[41](https://github.com/octodemo/colind-bookstore-v22/runs/8033399540?check_suite_focus=true#step:4:43)8)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand.resolveQuerySpecifier(ResolveQueriesCommand.java:229)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand.executeJSON(ResolveQueriesCommand.java:195)
  	at com.semmle.cli2.resolve.ResolveQueriesCommand.executeJSON(ResolveQueriesCommand.java:71)
  	at com.semmle.cli2.picocli.SimpleJsonSubcommand.executeInsistingOnJSON(SimpleJsonSubcommand.java:117)
  	at com.semmle.cli2.picocli.SimpleJsonSubcommand.executeSubcommand(SimpleJsonSubcommand.java:80)
  	at com.semmle.cli2.picocli.SubcommandCommon.call(SubcommandCommon.java:500)
  	at com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:205)
  	at com.semmle.cli2.picocli.SubcommandMaker.runMain(SubcommandMaker.java:214)
  	at com.semmle.cli2.CodeQL.main(CodeQL.java:98)
```

The contents of the selectors file (the target of the `apply`) can be anything: I tried copying the entire contents of some of the suite-helpers in the `misc` folder from this repo and I get the same error. It doesn't seem to be a problem with the _contents_ of the file.

I did notice that I can specify an apply for a well-known helper suite in the `.qls` file:

```yml
- description: Include low precision queries
- qlpack: codeql/java-queries
- apply: security-and-quality-selectors.yml
  from: codeql-suite-helpers
```

The above configuration works (no build failure).

The build also works if I copy the contents of the `apply` file into the `.qls` file entirely:

```yml
- description: Include low precision queries
- qlpack: codeql/java-queries
- include:
    kind:
    - problem
    - path-problem
    ...
```

It seems that there is an error when trying to apply filters using a custom `apply` file, unless I'm missing something.

**Comment by aibaars** [comment]
@colindembovsky Thanks for the detailed report! We should definitely fix the `NoSuchElementException` error and print a more informative message instead.

If I am not mistaken the value of `from:` property should be the name of a query pack, and not a file path. 

Does the following work?
```
- apply: ./.github/codeql/low-precision-selectors.yml
```

**Comment by colindembovsky** [comment]
Hi @aibaars thanks for the quick response! The full file does not appear to work.

```yml
- description: Include low precision queries
- qlpack: codeql/java-queries
- apply: ./.github/codeql/low-precision-selectors.yml
```

Now I get this error:

```
A fatal error occurred: /home/runner/work/colind-bookstore-v22/colind-bookstore-v22/.github/codeql/low-precision-queries.qls refers to a relative path "./.github/codeql/low-precision-selectors.yml" but is not in a pack, so we don't know what to resolve it against.
```

**Comment by aibaars** [comment]
@colindembovsky At least the error message is more descriptive this time. Apparently we cannot use a relative path unless we're in the context of a "query pack". 

Using an absolute path is probably not an option in this case :
```
- description: Include low precision queries
- qlpack: codeql/java-queries
- apply: /home/runner/work/colind-bookstore-v22/colind-bookstore-v22/.github/codeql/low-precision-selectors.yml
```

Alternatively, you could put a `qlpack.yml` file (similar to [suite-helpers](https://github.com/github/codeql/blob/main/misc/suite-helpers/qlpack.yml)) in the `.github/codeql` folder and write:
```
- description: Include low precision queries
- qlpack: codeql/java-queries
- apply: ./low-precision-selectors.yml
```

**Comment by colindembovsky** [comment]
@aibaars I haven't tried the absolute path, but the pack still doesn't seem to work:

```
A fatal error occurred: /home/runner/work/colind-bookstore-v22/colind-bookstore-v22/.github/codeql/low-precision-pack.qls refers to a relative path "./low-precision-selectors.yml" but is not in a pack, so we don't know what to resolve it against.
```

**Comment by colindembovsky** [comment]
The absolute path works - but I cannot get a relative path to work. This isn't ideal since the abs path is going to change. I could use `sed` or something to inject the path, but that seems hacky.

**Comment by aeisenberg** [comment]
As @aibaars has already mentioned, relative paths must be relative to a qlpack. Otherwise, the path must be absolute.

There is a new feature, just released this week, called query-filters. Documentation for this is coming soon. Since you are using the codeql-action, You just need to augment your code scanning config file like this:

```yml
name: "Custom CodeQL Config"
disable-default-queries: true
packs:
  java:
    - codeql/java-queries
query-filters:
- exclude:
    ...
- include
   ...
```

The `packs` block contains the list of qlpacks to run. The `query-filters` block contains a list of include and exclude instructions from your query suite. Assuming that your `low-precision-selectors.yml` file is just a bunch of include and exclude instructions, you should be able to copy them directly into the query-filters block. With this, you won't need your custom `low-precision-queries.qls` file or  `low-precision-selectors.yml` file.

This should simplify things for you. Please let me know if it works.

**Comment by colindembovsky** [comment]
Thanks @aeisenberg ! That _appeared_ to work - at least the init didn't crash. However, I'm not seeing any difference in the queries selected. I'm trying to "dial down the precision" on the default Java queries. Here's what I'm attempting:

```yml
name: "Custom CodeQL Config for lower precision"
disable-default-queries: true
packs:
  java:
    - codeql/java-queries
query-filters:
- include:
    kind:
    - problem
    - path-problem
    - alert
    - path-alert
    precision:
    - low
    - medium
    - high
    - very-high
    tags contain:
    - security
    - correctness
    - maintainability
    - readability
- include:
    kind:
    - problem
    - path-problem
    precision:
    - medium
    problem.severity:
    - error
    - warning
    - recommendation
    tags contain:
    - security
- include:
    kind:
    - diagnostic
- include:
    kind:
    - metric
    tags contain:
    - summary
- exclude:
    deprecated: //
- exclude:
    query path:
      - /^experimental\/.*/
      - Metrics/Summaries/FrameworkCoverage.ql
      - /Diagnostics/Internal/.*/
- exclude:
    tags contain:
      - model-generator
```

However, if I enable debugging and download the SARIF I can see that there are 0 results and the queries between this and no filters _are exactly the same_. Is there another way to add in less precise queries?

**Comment by aeisenberg** [comment]
So, this piece:

```yml
packs:
  java:
    - codeql/java-queries
```

Runs the default query suite of the java pack, which uses [`code-scanning-selectors.yml`](https://github.com/github/codeql/blob/main/misc/suite-helpers/code-scanning-selectors.yml). This does not include the less precise queries.

In order to add the less precise queries, you need to use a different set of magic options:

```yml
name: "CodeQL config"
queries: 
  - uses: security-extended
  - uses: security-and-quality
query-filters:
... as above ...
```

No need to explicitly add a `packs` block. Since the action will automatically use the java pack and extend it woth the two extra suites `security-extended` and `security-and-quality`.

**Comment by colindembovsky** [comment]
Thanks for all the help @aibaars and @aeisenberg - looks like I'm able to get some less precise query results using this config:

```yml
name: "Custom CodeQL Config for lower precision"
disable-default-queries: true
queries:
  - uses: security-extended
  - uses: security-and-quality
query-filters:
- include:
    kind:
    - problem
    - path-problem
    - alert
    - path-alert
    precision:
    - low
    - medium
    - high
    - very-high
    tags contain:
    - security
    - correctness
    - maintainability
    - readability
- include:
    kind:
    - problem
    - path-problem
    precision:
    - medium
    problem.severity:
    - error
    - warning
    - recommendation
    tags contain:
    - security
- include:
    kind:
    - diagnostic
- include:
    kind:
    - metric
    tags contain:
    - summary
- exclude:
    deprecated: //
- exclude:
    query path:
      - /^experimental\/.*/
      - Metrics/Summaries/FrameworkCoverage.ql
      - /Diagnostics/Internal/.*/
- exclude:
    tags contain:
      - model-generator
```
