### ISSUE TITLE
Test kotlin support

### ISSUE THREAD

**Issue by weddige** [github/codeql#10590]
**Description of the issue**

I'm aware, that kotlin support is not official yet (https://github.com/github/roadmap/issues/207). However, codeql already contains a [kotlin extractor](https://github.com/github/codeql/tree/main/java/kotlin-extractor). Is it somehow possible to use that to create a database?

Looking ath the file types in `\java\codeql-extractor.yml`, I assumed it should be possible to run codeql with `-l java`, but so far my database didn't contain any code.

```yaml
file_types:
  - name: java
    display_name: Java sources
    extensions:
      - .java
  - name: kotlin
    display_name: Kotlin sources
    extensions:
      - .kt
```

Any help to test the (currently unfinished and unsupported) kotlin support would be appreciated.
