### ISSUE TITLE
Autobuild C#: environment variables availability in dotnet / msbuild

### ISSUE THREAD

**Issue by joshcampbell191** [github/codeql#11425]
**Description of the issue**

When building a C# project on ubuntu, I noticed that `env` variables passed to the `autobuild` task aren't available to `dotnet` / `msbuild`. Is this by design?

```yml
- name: Autobuild
  uses: github/codeql-action/autobuild@v2
  env:
    PP_TOOLS_TELEMETRY_OPTOUT: true
```
