### ISSUE TITLE
Use Cli to analyze database but get no result

### ISSUE THREAD

**Issue by icy17** [github/codeql#11878]
Hi, I write a ql like:

```
/**
 * @name test_compile
 * @description test if target is compiled
 * @kind problem
 * @severity error
 * @id cpp/test-compile
 * @tags security
 */

import cpp
from FunctionCall fc
where 
fc.getTarget().hasName("av_dict_set") 
select  fc, fc.getLocation().toString()
```
I am sure there are some function calls, but the result is none.
And I found this situation maybe related with the `sourceLocationPrefix` ? I compile this software in one machine, and query this database in the other machine. And I found that in analyse log:
`[2023-01-12 21:13:24] [SPAMMY] database interpret-results> Skipping location 'file:///root/output/ffmpeg/HandBrake/libhb/decavcodec.c:1819:13:1819:23' since it is outside the source archive.`

But I change `sourceLocationPrefix` to the source code dir, and the log is the same. I can't get the right result in my output file. What can I do to solve this problem?

**Comment by jketema** [comment]
Hi @icy17 

Thanks for your question.

> I compile this software in one machine, and query this database in the other machine.

This shouldn't be a problem, and is something we do routinely. May I ask what exactly copied from one machine to another (I'm interested in the directory contents)?

**Comment by icy17** [comment]
@jketema Thank you for your reply!
I copy the database dir:
![image](https://user-images.githubusercontent.com/39425646/212220862-0a8aa0fa-86ae-483b-b77a-60148492b6f2.png)
And the codeql-database.yml is:
```
---
sourceLocationPrefix: "/root/output/ffmpeg/HandBrake/build"
baselineLinesOfCode: 2227454
unicodeNewlines: false
columnKind: "utf8"
primaryLanguage: "cpp"
creationMetadata:
  cliVersion: "2.11.1"
  creationTime: "2023-01-12T08:34:17.682938669Z"

```

I run a query, and I found that:
`[SPAMMY] database interpret-results> Skipping location 'file:///root/output/ffmpeg/HandBrake/libhb/decavcodec.c:1819:13:1819:23' since it is outside the source archive.`
And I unzip the src.zip to get the source code, then I change the codeql-database.yml to:


```
sourceLocationPrefix: "/home/jhliu/database/ffmpeg/HandBrake-82905bb/root/output/ffmpeg/HandBrake/build/"
baselineLinesOfCode: 2227454
unicodeNewlines: false
columnKind: "utf8"
primaryLanguage: "cpp"
creationMetadata:
  cliVersion: "2.11.1"
  creationTime: "2023-01-12T08:34:17.682938669Z"
```
but when I run the query again, I got the same result....:

I don't know why. I have changed the sourceLocationPrefix, why the log writes:'file:///root/output/ffmpeg/HandBrake/libhb/decavcodec.c?
Did I do something wrong?
