### ISSUE TITLE
False positive: (C++) The use of 'localtime' reported despite that it's nowhere used

### ISSUE THREAD

**Issue by ethouris** [github/codeql#12087]
**Description of the false positive**

Reported is "Use of the potentially dangerous function" - "Call to 'localtime' is potentially dangerous". The location pointed by the report is `CMakeFiles/CMakeScratch/TryCompile-AmO6Yy/src.cxx:9` and preview is not available. This location doesn't exist on the repository, it's clearly a part of the build, but according to what was hinted by the CMake's documentation, this kind of path is being used (that is, created as temporary) by the `try_compile` cmake function. In this project this function also isn't used anywhere so I assume it's being used by the CodeQL system.

**Code samples or links to source code**

The project in question is [SRT](https://github.com/Haivision/srt) and [this pull request](https://github.com/Haivision/srt/pull/2644) has been prepared to track this problem; as of the version from which it was spawned, the CodeQL problem is [reported there too](https://github.com/Haivision/srt/security/code-scanning/150).

**Comment by jketema** [comment]
Hi @ethouris 

Thanks for your report.

As you specify explicit build command in the SRT CodeQL workflow file, CodeQL only traces the compiler invocations that are issued by your build system. CodeQL will not itself try to invoke any build/CMake related commands and, hence, cannot cause any additional files to be created/analyzed.

CodeQL will pick up on any C/C++ file that is compiled during the build even temporary ones that CMake might create. If we detect issues with these generated files, an alert will be raised, but the source contents when viewing the alert will be empty, because the file does not occur in your repository.

What is not clear to me from your report is the following: does the problem you describe only occur when you pass the `--debug-trycompile` flag, or does it also occur without it? If it only occurs when the flag is being passed, are you sure `--debug-trycompile` does not cause the file to be created?

**Comment by ethouris** [comment]
It occurs always. I added the `--debug-trycompile` flag in the PR I have linked this report to it as an attempt to track the problem. It changes nothing, including not helping in this effort at all.

Might be that we use this tool incorrectly, but I don't know what I'm doing wrong. It's expected that CodeQL traces even the generated code, but not exactly that it traces the temporary code generated by the build tool to autodetect system properties. Maybe this command should be placed in a different section or something like this. Could you help?

**Comment by jketema** [comment]
Hi @ethouris 

Thanks for the additional info.

> Might be that we use this tool incorrectly, but I don't know what I'm doing wrong. It's expected that CodeQL traces even the generated code, but not exactly that it traces the temporary code generated by the build tool to autodetect system properties. Maybe this command should be placed in a different section or something like this. Could you help?

Looking at your workflow again, I see the following:

```yaml
      - name: Configure
        run: cmake . -DENABLE_HEAVY_LOGGING=1 -DENABLE_BONDING=1

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          queries: +security-and-quality

      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fpermissive -DENABLE_BONDING=ON .
          make
```

So it looks like you're re-running CMake during the build step. This probably triggers it's detection code, and an associated compiler invocation on one of the temporary files generated my CMake. A tigger is likely, as the flags you're passing differ from those you passed in the configuration step (there are additional `-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fpermissive`).

Maybe you're tried this already, but you probably want to rewrite the above snipped to be as follows (I'm not sure if you need the `-DENABLE_HEAVY_LOGGING=1` in the CMake invocation):
```
      - name: Configure
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-fpermissive -DENABLE_BONDING=ON .

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          queries: +security-and-quality

      - name: Build
        run: |
          make
```

If the above does not work, what kind of failures are you seeing?
