### ISSUE TITLE
General issue

### ISSUE THREAD

**Issue by ka1n4t** [github/codeql#13193]
**Description of the issue**
*** Question1 ***
Hi, I got a problem when I try to create database for a golang codebase.

env:
macos:12.0.1
codeql:2.13.1

command:
```
codeql database create /home/work/codeql_db/xxx  --language=go --command="make all -f Makefile" --overwrite
```

console error log:
```
CodeQL detected code written in Go but could not process any of it. This can occur if the specified build commands failed to compile or process any code.
 - Confirm that there is some source code for the specified language in the project.   <----------note, confirmed
 - For codebases written in Go, JavaScript, TypeScript, and Python, do not specify 
   an explicit --command.
 - For other languages, the --command must specify a "clean" build which compiles 
   all the source code files without reusing existing build artefacts.
```

codeql-database.yml :
```
cat ../xxx/codeql-database.yml 
---
sourceLocationPrefix: /home/work/workdir/dxm/aaa/bbb
baselineLinesOfCode: 6372
unicodeNewlines: false
columnKind: utf8
primaryLanguage: go
inProgress:
  primaryLanguage: go
  installedExtractors:
    javascript:
     - /home/work/soft/codeql/javascript
    java:
     - /home/work/soft/codeql/java
    ruby:
     - /home/work/soft/codeql/ruby
    csharp:
     - /home/work/soft/codeql/csharp
    python:
     - /home/work/soft/codeql/python
    go:
     - /home/work/soft/codeql/go
    cpp:
     - /home/work/soft/codeql/cpp
    yaml:
     - /home/work/soft/codeql/yaml
    properties:
     - /home/work/soft/codeql/properties
    xml:
     - /home/work/soft/codeql/xml
    html:
     - /home/work/soft/codeql/html
    csv:
     - /home/work/soft/codeql/csv
creationMetadata:
  cliVersion: 2.13.1
  creationTime: 2023-05-17T03:25:11.140072462Z
finalised: false
```

*** Question2 ***
Does codeql support multi commands like `--command="cd ../../ && ..... && make Makefile"`? I ran the whole command, codeql return message like question1. But it generate database successfully when I just run `--command="make Makefile"`.
