### ISSUE TITLE
Can't skip CodeQL if the status check is set required

### ISSUE THREAD

**Issue by chris-jenkinson** [github/codeql#13932]
My repo is set with a branch protection rule requiring the CodeQL status check. My yml names the action as "CodeQL" and the auto-complete in the branch protection settings knows the status check as "CodeQL".

I do not want CodeQL to run when Dependabot creates a PR, so in my yml I have an `if` that skips the run per [the dependabot documentation](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions):

```
name: "CodeQL"

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    if: ${{ github.triggering_actor != 'dependabot[bot]' }} # don't run if dependabot initiated the PR
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp', 'javascript' ]
   ...
```

Dependabot creates the PR and the CodeQL does not run. However, despite the [documentation](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/about-status-checks) stating that skipped statuses report as successful, this is not the case. The `CodeQL/Analyze` shows skipped, but the `CodeQL` action is still waiting for status. I cannot put "CodeQL/Analyze" as a required status check, only `CodeQL` is accepted.

![image](https://github.com/github/codeql/assets/74602418/a46a71a6-1855-4e9a-8776-303be5b01f25)
