### ISSUE TITLE
Extraction is broken with Swift 5.9 toolchain

### ISSUE THREAD

**Issue by gwynne** [github/codeql#14300]
A straightforward CodeQL workflow (see below) works as written when a Swift 5.8 image is used, but when switched to the recent Swift 5.9 release, CodeQL fails to extract any symbols.

```yml
name: CodeQL
on:
  push:
jobs:
  analyze:
    runs-on: ubuntu-latest
    container: swift:5.9-jammy
    permissions: { actions: write, contents: read, security-events: write }
    timeout-minutes: 60
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with: { languages: swift }
      - name: Perform build
        run: swift build
      - name: Run CodeQL analyze
        uses: github/codeql-action/analyze@v2
```

Note: I am aware of support for auto build- this is a simplified version of the actual workflow, which needs more control over the actual build invocation. This simplified version fails in exactly the same way as the "real" one, regardless of what code is being build. The exact same failure also occurs if not using a `container`, and even with a macOS runner.
