### ISSUE TITLE
Pack 'codeql/javascript-all' was not found locally, and is not listed in the lock file. Run 'codeql pack install' to update the lock file and download the dependencies.

### ISSUE THREAD

**Issue by nagarrianharshit** [github/codeql#14559]
I have created a database locally for my javascript code base, next I selected that database in codeql extension, then I created query.ql file inside Database folder, in the same database folder i also created qlpack.yml with content:
```
name: codeql/javascript-examples
groups: 
  - javascript
  - examples
dependencies:
  codeql/javascript-all: '*'
  ```
  Here when i hover on name it shows error: Pack 'codeql/javascript-all' was not found locally, and is not listed in the lock file. Run 'codeql pack install' to update the lock file and download the dependencies.
  
  Here I also performed codeql pack install and got the output :
```
  Dependencies resolved. Installing packages...
Install location: C:\Users\harshitjain04\.codeql\packages
Nothing to install.
Package install location: C:\Users\harshitjain04\.codeql\packages
Nothing downloaded.
```
I have noticed that there is no packages folder present in .codeql

**Comment by aibaars** [comment]
For me it seems to work fine, I get the following output:
```
$ cat > qlpack.yml
name: codeql/javascript-examples
groups: 
  - javascript
  - examples
dependencies:
  codeql/javascript-all: '*'

$ codeql pack install
Dependencies resolved. Installing packages...
Install location: /Users/me/.codeql/packages
Package install location: /Users/me/.codeql/packages
Installed fresh codeql/javascript-all@0.8.1 (library)
Installed fresh codeql/mad@0.2.1 (library)
Installed fresh codeql/regex@0.2.1 (library)
Installed fresh codeql/tutorial@0.2.1 (library)
Installed fresh codeql/util@0.2.1 (library)
Installed fresh codeql/yaml@0.2.1 (library)
```

Did you run `codeql pack install` in/on the folder containing the `qlpack.yml` file? 

The result of running the command is a `codeql-pack.lock.yml` with contents like:
``` 
---
lockVersion: 1.0.0
dependencies:
  codeql/javascript-all:
    version: 0.8.1
  codeql/mad:
    version: 0.2.1
  codeql/regex:
    version: 0.2.1
  codeql/tutorial:
    version: 0.2.1
  codeql/util:
    version: 0.2.1
  codeql/yaml:
    version: 0.2.1
compiled: false
```
