### ISSUE TITLE
General issue [Azure DevOps Pipeline]: pipeline is stuck at "Starting evaluation of codeql/csharp-queries/Telemetry/UnsupportedExternalAPIs.ql." step

### ISSUE THREAD

**Issue by ibrahim-amer** [github/codeql#15059]
I am adding CodeQL checks to our repository for it to run when code is pushed to our branch. The code ql analyze task never finishes and it always stuck until the task fails at this step "Starting evaluation of codeql/csharp-queries/Telemetry/UnsupportedExternalAPIs.ql." of running "AdvancedSecurity-Codeql-Analyze@1" task in an AzureDevOps Pipeline. 

Here is my yaml file's content: 
```


trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  #advancedsecurity.codeql.querysuite: security-extended
  #advancedsecurity.submittoadvancedsecurity: true
  timeoutInMinutes: 360

steps:
  - task: AdvancedSecurity-Codeql-Init@1
    inputs:
      languages: 'csharp'

  - task: AdvancedSecurity-Codeql-Autobuild@1
  - task: AdvancedSecurity-Dependency-Scanning@1
  - task: AdvancedSecurity-Codeql-Analyze@1
```
