### ISSUE TITLE
codeql sometimes tries to automatically builds the code

### ISSUE THREAD

**Issue by eiffel-fl** [github/codeql#15405]
Hi!

I use `codeql` in my repository to analyze the code base searching for CWE.
Sadly, for some analysis, the process takes a long time.
I dived into it and saw that sometimes, `codeql` tries to automatically builds the code while the other it does not.
Note that, the binaries to analyze were all built in the previous step.
As a result, building the code takes time but `codeql` also downloads data which takes an extra amount of time:

```
Attempting to automatically build go code
...
go build -ldflags "-X github.com/inspektor-gadget/inspektor-gadget/cmd/common.version=`git describe --tags --always` -X main.gadgetimage=inspektor-gadget/inspektor-gadget:latest -extldflags '-static'" \
  	-tags withoutebpf \
  	-o kubectl-gadget-${GOOS}-${GOARCH} \
  	github.com/inspektor-gadget/inspektor-gadget/cmd/kubectl-gadget
  cp kubectl-gadget-linux-amd64 kubectl-gadget
  if false == "true" ; then \
  	./tools/getbtfhub.sh && \
  	make -f Makefile.btfgen \
  		BTFHUB_ARCHIVE=/home/runner/btfhub-archive/ -j; \
  fi
  docker buildx build --load -t inspektor-gadget/inspektor-gadget:latest \
  	-f Dockerfiles/gadget.Dockerfile .
  #0 building with "default" instance using docker drive
...
  2024/01/22 11:35:41 Running extractor command '/opt/hostedtoolcache/CodeQL/2.16.0/x64/codeql/go/tools/linux64/go-extractor [./...]' from directory '.'.
  2024/01/22 11:35:41 Build flags: ''; patterns: './...'
  2024/01/22 11:35:41 Running packages.Load.
  2024/01/22 11:35:47 Done running packages.Load.
...
   2024/01/22 11:40:37 Done extracting packages. 
```

For reference, here are two links to our YAML:
1. Where the autobuild does not occur: https://github.com/inspektor-gadget/inspektor-gadget/blob/ceb9570aeaf02757ffd73c6b4d9fff334f3ca9e0/.github/workflows/inspektor-gadget.yml#L202-L211 and https://github.com/inspektor-gadget/inspektor-gadget/blob/ceb9570aeaf02757ffd73c6b4d9fff334f3ca9e0/.github/workflows/inspektor-gadget.yml#L242-L243
2. Where it occurs: https://github.com/inspektor-gadget/inspektor-gadget/blob/ceb9570aeaf02757ffd73c6b4d9fff334f3ca9e0/.github/workflows/inspektor-gadget.yml#L319-L322 and https://github.com/inspektor-gadget/inspektor-gadget/blob/ceb9570aeaf02757ffd73c6b4d9fff334f3ca9e0/.github/workflows/inspektor-gadget.yml#L340-L341

The only difference between the two analysis lies in the env as when trying to autobuild it contains a lot of `CODEQL_*` variables:

```
Run github/codeql-action/analyze@v3
  with:
    output: ../results
    upload: always
    cleanup-level: brutal
    add-snippets: false
    skip-queries: false
    checkout_path: /home/runner/work/inspektor-gadget/inspektor-gadget
    upload-database: true
    wait-for-processing: true
    token: ***
    matrix: {
    "platform": "amd64"
  }
    expect-error: false
  env:
    REGISTRY: ghcr.io
    CONTAINER_REPO: inspektor-gadget/inspektor-gadget
    GO_VERSION: 1.21.3
    AZURE_AKS_CLUSTER_PREFIX: ig-ci-aks-
    DEFAULT_DNSTESTER_IMAGE: ghcr.io/inspektor-gadget/dnstester:latest
    DEFAULT_EBPF_BUILDER_IMAGE: ghcr.io/inspektor-gadget/ebpf-builder:latest
    CODEQL_ACTION_FEATURE_MULTI_LANGUAGE: false
    CODEQL_ACTION_FEATURE_SANDWICH: false
    CODEQL_ACTION_FEATURE_SARIF_COMBINE: true
    CODEQL_ACTION_FEATURE_WILL_UPLOAD: true
    CODEQL_ACTION_VERSION: 3.23.1
    JOB_RUN_UUID: b79863f2-d27a-49b5-8f1c-73031619a546
    CODEQL_ACTION_ANALYSIS_KEY: .github/workflows/inspektor-gadget.yml:build-ig
    CODEQL_WORKFLOW_STARTED_AT: 2024-01-22T11:30:08.548Z
    CODEQL_ACTION_GO_BINARY: /home/runner/work/_temp/codeql-action-go-tracing/bin/go
    CODEQL_RAM: 14567
    CODEQL_THREADS: 4
    CODEQL_EXTRACTOR_PYTHON_DISABLE_LIBRARY_EXTRACTION: true
    CODEQL_SCRATCH_DIR: /home/runner/work/_temp/codeql_databases/working
    CODEQL_DIST: /opt/hostedtoolcache/CodeQL/2.16.0/x64/codeql
    CODEQL_PLATFORM: linux64
    CODEQL_PLATFORM_DLL_EXTENSION: .so
    CODEQL_JAVA_HOME: /opt/hostedtoolcache/CodeQL/2.16.0/x64/codeql/tools/linux64/java
    CODEQL_EXTRACTOR_GO_ROOT: /opt/hostedtoolcache/CodeQL/2.16.0/x64/codeql/go
    CODEQL_EXTRACTOR_GO_WIP_DATABASE: /home/runner/work/_temp/codeql_databases/go
    CODEQL_EXTRACTOR_GO_DIAGNOSTIC_DIR: /home/runner/work/_temp/codeql_databases/go/diagnostic/extractors/go
    CODEQL_EXTRACTOR_GO_LOG_DIR: /home/runner/work/_temp/codeql_databases/go/log
    CODEQL_EXTRACTOR_GO_SCRATCH_DIR: /home/runner/work/_temp/codeql_databases/go/working
    CODEQL_EXTRACTOR_GO_TRAP_DIR: /home/runner/work/_temp/codeql_databases/go/trap/go
    CODEQL_EXTRACTOR_GO_SOURCE_ARCHIVE_DIR: /home/runner/work/_temp/codeql_databases/go/src
    SEMMLE_HANDLE_STATIC_BINARIES: true
    CODEQL_EXTRACTOR_GO_THREADS: 4
    CODEQL_EXTRACTOR_GO_RAM: 14567
    CODEQL_TRACER_LOG: /home/runner/work/_temp/codeql_databases/log/build-tracer.log
    CODEQL_TRACER_DIAGNOSTICS_DIR: /home/runner/work/_temp/codeql_databases/diagnostic/tracer
    CODEQL_TRACER_LANGUAGES: go
    SEMMLE_PRELOAD_libtrace: /opt/hostedtoolcache/CodeQL/2.16.0/x64/codeql/tools/linux64/${LIB}_${PLATFORM}_trace.so
    SEMMLE_PRELOAD_libtrace32: /opt/hostedtoolcache/CodeQL/2.16.0/x64/codeql/tools/linux64/lib32trace.so
    SEMMLE_PRELOAD_libtrace64: /opt/hostedtoolcache/CodeQL/2.16.0/x64/codeql/tools/linux64/lib64trace.so
    LD_PRELOAD: /opt/hostedtoolcache/CodeQL/2.16.0/x64/codeql/tools/linux64/${LIB}_${PLATFORM}_trace.so
    CODEQL_RUNNER: /opt/hostedtoolcache/CodeQL/2.16.0/x64/codeql/tools/linux64/runner
```

Can you please shed some light on this behavior?

Best regards.
```[tasklist]
### Tasks
```
