### ISSUE TITLE
`.github/workflows/qhelp-pr-preview.yml` shouldn't upload-artifact if `cancelled()`

### ISSUE THREAD

**Issue by jsoref** [github/codeql#15588]
https://github.com/check-spelling-sandbox/codeql/actions/runs/7878366188

[qhelp](https://github.com/check-spelling-sandbox/codeql/actions/runs/7878366188/job/21496467354#step:5:44)
The operation was canceled.
[qhelp](https://github.com/check-spelling-sandbox/codeql/actions/runs/7878366188/job/21496467354#step:8:10)
No files were found with the provided path: comment_body.txt. No artifacts will be uploaded.

https://github.com/check-spelling-sandbox/codeql/actions/runs/7878366188/workflow

```yaml

      - if: always()
        uses: actions/upload-artifact@v3
        with:
          name: comment
          path: comment_body.txt
          if-no-files-found: error
          retention-days: 1
```

https://github.com/check-spelling-sandbox/codeql/actions/runs/7878366188/job/21496467354#step:8:10

The docs for [`always()`](https://docs.github.com/en/actions/learn-github-actions/expressions#always) say:

> Warning: Avoid using always for any task that could suffer from a critical failure, for example: getting sources, otherwise the workflow may hang until it times out. If you want to run a job or step regardless of its success or failure, use the recommended alternative: `if: ${{ !cancelled() }}`
