### ISSUE TITLE
Issues found but "Sorry, we couldn't find this file in the repository."

### ISSUE THREAD

**Issue by parsley72** [github/codeql#15787]
I've got CodeQL running on my repo and it's finding issues but they all say "Sorry, we couldn't find this file in the repository."

Because the repo is used in a Yocto build, when the GitHub Action checks out the source code it's moved into a subdirectory (let's say mydirectory/source/myapp) so the build can be run. The analysis seems to be working fine but the issues are listed in files like mydirectory/source/myapp/main.cpp:127.

Is there any way of making CodeQL use the git info for the files (which is still present), or telling it how file locations relate to the repo?

**Comment by parsley72** [comment]
I thought I could fix this with https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/sarif-support-for-code-scanning#specifying-the-root-for-source-files but I'm having trouble getting it to work. This:
```
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
        checkout_path: mydirectory/source/myapp
```
seems to do the opposite - I'm now seeing:
Uploading results
  Processing sarif files: ["/home/runner/work/githubproject/results/cpp.sarif"]
  ##[debug]Unable to compute fingerprint for non-existent file: mydirectory/source/myapp//mydirectory/source/myapp/logger.h
Have I misunderstood how this is supposed to work?

**Comment by parsley72** [comment]
After reading the test https://github.com/github/codeql-action/blob/main/.github/workflows/__with-checkout-path.yml I tried adding `source-root` to the `init` step as well:
```
    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        source-root: mydirectory/source/myapp
```
along with:
```
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
        checkout_path: mydirectory/source/myapp
```
This works - I'm now seeing the files located correctly.
