### ISSUE TITLE
[Question][Java] Yaml summaryModel question

### ISSUE THREAD

**Issue by chmodxxx** [github/codeql#15932]
Hello 

I have the following two passthroughs that I want to model using yaml summaryModel :

1. AuthHeader.of(authHeader)    : I want to pass the flow from the arg to the Qualifier
2. token.getBearerToken() : I want to pass the flow from the qualifier token to the result 

This is my current yaml model : 

```
extensions:
  - addsTo:
      pack: org/repo
      extensible: summaryModel
    data:
      - ["com.foo.bar", "AuthHeader", True, "getBearerToken", "()", "", "Argument[this]", "ReturnValue", "taint", "manual"]
      - ["com.foo.bar", "AuthHeader", True, "of", "", "", "Argument[0]", "Argument[this]", "taint", "manual"]
      
```

For some reason this is not propagating in expressions like `AuthHeader ah = AuthHeader.of(AuthHeader.of(AuthHeader.of(token).getBearerToken()).getBearerToken());` 

Is there something I missed ? 

I also tried with having of() propagating from Argument[0] to ReturnValue but also didn't work
