### ISSUE TITLE
Kotlin: "CodeQL currently supports versions below 2.1.10"

### ISSUE THREAD

**Issue by spyro2000** [github/codeql#18596]
Is there any update planed on this? Why is 2.1.9 ok, but 2.1.10 is breaking...?
For whatever reason, the Kotlin team decided to go from 2.1 directly to 2.1.10. Next one will bei 2.1.20. Each incremental step will break CodeQL again, correct?

**Comment by spyro2000** [comment]
Never mind, seems like our TI just uses an outdated version (AFAIK 2.1.10 should work according to https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/ it's "2.1.2x")

**Comment by edgarvonk** [comment]
We are running into the same issue and we are using the most recent version of the [CodeQL GitHub actions](https://github.com/github/codeql-action/pkgs/container/codeql-action) (v3.28.5).

**Comment by edgarvonk** [comment]
This issue started occurring for us when we upgraded from Kotlin 2.1.9 to 2.1.10. As said the CodeQL GitHub action we use is that latest (v3.28.5). Part of the stacktrace from our GitHub CodeQL workflow:

```
  [2025-01-27 10:28:36] [autobuild] e: com.semmle.extractor.java.interceptors.KotlinInterceptor$KotlinVersionTooRecentError: Kotlin version 2.1.10 is too recent. CodeQL currently supports versions below 2.1.10
  [2025-01-27 10:28:36] [autobuild] 	at com.semmle.extractor.java.interceptors.KotlinInterceptor.getExtractorJarPath(KotlinInterceptor.java:247)
  [2025-01-27 10:28:36] [autobuild] 	at com.semmle.extractor.java.interceptors.KotlinInterceptor.beforeKotlinExecute(KotlinInterceptor.java:589)
  [2025-01-27 10:28:36] [autobuild] 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.SEMMLE_INTERCEPT$0(K2JVMCompiler.kt)
```

**Comment by jacq42** [comment]
Hi @rvermeulen,

we run into the same issue.

We use CodeQL with the latest GitHub CodeQL Action:
```
github/codeql-action/init@v3
github/codeql-action/analyze@v3
```

That uses CodeQL version 2.20.3:
`Using CodeQL CLI version 2.20.3 sourced from https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.20.3/codeql-bundle-linux64.tar.zst .`

**Comment by edgarvonk** [comment]
Hi @rvermeulen , same as above. Our CodeQL GitHub workflow uses CodeQL version 2.20.3 looking at the logs:

```CODEQL_JAVA_HOME: /opt/hostedtoolcache/CodeQL/2.20.3/x64/codeql/tools/linux64/java```

ps: you mean Kotlin 2.1.10 I think?

**Comment by edgarvonk** [comment]
This is our GitHub CodeQL workflow step just to be complete:

```
  analyze:
    name: Analyze
    runs-on: ubuntu-24.04
    needs: paths-ignore
    if: ${{ needs.paths-ignore.outputs.skip != 'true' }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: ["java-kotlin", "javascript-typescript", "actions"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup JDK
        if: matrix.language == 'java-kotlin'
        uses: actions/setup-java@7a6d8a8234af8eb26422e24e3006232cccaa061b # v4.6.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: "temurin"

      - name: Setup Gradle
        if: matrix.language == 'java-kotlin'
        uses: gradle/actions/setup-gradle@0bdd871935719febd78681f197cd39af5b6e16a6 # v4.2.2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@b6a472f63d85b9c78a3ac5e89422239fc15e9b3c # v3.28.1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@b6a472f63d85b9c78a3ac5e89422239fc15e9b3c # v3.28.1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@b6a472f63d85b9c78a3ac5e89422239fc15e9b3c # v3.28.1
        with:
          category: "/language:${{matrix.language}}"
```
