### ISSUE TITLE
`js/weak-cryptographic-algorithm`/`BrokenCryptoAlgorithm` got 25-30x slower

### ISSUE THREAD

**Issue by maschwenk** [github/codeql#18604]
**Description of the issue**

Similar to

- https://github.com/github/codeql/issues/18584

this rule appears to run 20-30x slower on the same exact repo with the same hardware

```
[106/106 eval 30m34s] Evaluation done; writing results to codeql/javascript-queries/Security/CWE-327/BrokenCryptoAlgorithm.bqrs.
```

unsure root cause is the same as the other issue, but disabling rule rule like

```yaml
query-filters:
  - exclude:
      id: js/weak-cryptographic-algorithm
```
is a workaround
