### ISSUE TITLE
JS/TS Analyse 2.20.4 Runs Extremely Slow

### ISSUE THREAD

**Issue by aaronmassicotte** [github/codeql#18736]
Pipelines had been taking >90m to run the CodeQL `github/codeql-action/analyze@v3` step sicne 2.20.4. When reverting back to 2.20.3 via 

```yaml
...
      - name: "Initialize CodeQL"
        uses: github/codeql-action/init@v3
        with:
          tools: https://github.com/github/codeql-action/releases/download/codeql-bundle-v2.20.3/codeql-bundle-linux64.tar.zst
          languages: javascript-typescript
...
```
the issue is resolved. It is difficult to see why this is happening, but in our case the codebase is large (`CodeQL scanned 8401 out of 8401 TypeScript files and 1568 out of 1569 JavaScript files in this invocation.`). Normal runtime for this job is about 10 minutes with 32 GB memory and 40 (32 effective) CPUs

Let me know if I can help resolve the issue by providing additional details about the codebase. I suspect something in particular about this codebase may be running inefficiently, as no other enterprise-wide JS/TS scans have been impacted so far
