### ISSUE TITLE
False positive for GitHub action using a Docker image pinned by sha256

### ISSUE THREAD

**Issue by martincostello** [github/codeql#18782]
**Description of the false positive**

The new `actions` analysis identifies a false positive for actions using Docker images that are pinned by their container image SHA:

```yaml
- name: Lint workflows
  uses: docker://rhysd/actionlint@sha256:887a259a5a534f3c4f36cb02dca341673c6089431057242cdc931e9f133147e9 # v1.7.7
  with:
    args: -color
```

**Code samples or links to source code**

https://github.com/martincostello/costellobot/blob/3ec06e8bda448ba94c0bb1ad2bcdbdff85e13878/.github/workflows/lint.yml#L41-L44

**URL to the alert on GitHub code scanning (optional)**

https://github.com/martincostello/costellobot/security/code-scanning/183

![Image](https://github.com/user-attachments/assets/083c46b6-f30a-4811-bd19-cb106a9c35a1)
