### ISSUE TITLE
[actions] Add detection for workflow_dispatch TOCTOU

### ISSUE THREAD

**Issue by AdnaneKhan** [github/codeql#19835]
**Description of the issue**

There is a newer variation of GitHub Actions TOCTOU vulnerabilities known as "Workflow dispatch TOCTOU" - I wrote about a real-world example in a recent bug report writeup:

https://adnanthekhan.com/posts/dependabot-core-toctou-writeup/

I think this is a good candidate for a `High` detection where a PR has the following characteristics:

* Runs on workflow dispatch / repository dispatch with the PR number as an input parameter. Does NOT require a commit SHA.
* Checks out code from that PR without some approval check.
* Runs code.

High because there is a lot of context required to understand if a maintainer would _actually_ ever run the workflow on a fork, and that is not possible to determine via static analysis alone.

I believe this would require some code changes in the library code - adding a concept of a non externally triggered workflow that is intended to act upon untrusted code. This could then fire the UntrustedCheckoutTOCTOU alert

**Comment by rvermeulen** [comment]
Hi @AdnaneKhan,

Thanks for the suggestion.
Have you tried or looked at https://github.com/github/codeql/tree/main/actions/ql/src/Security/CWE-367?

**Comment by AdnaneKhan** [comment]
Hmm - I look a closer look and while it _seems_ like it would catch this, the `workflow_dispatch` trigger only leads to results when the workflow is pulling some untrusted context and then using some untrusted context and acting upon it.

From https://github.com/github/codeql/blob/c4a385fa6a9f4b16c55c5368573e4b4bb10f7c8e/actions/ql/lib/ext/config/externally_triggereable_events.yml#L19:

```
extensions:
  - addsTo:
      pack: codeql/actions-all
      extensible: externallyTriggerableEventsDataModel
    data:
      - ["discussion"]
      - ["discussion_comment"]
      - ["fork"]
      - ["watch"]
      - ["issue_comment"]
      - ["issues"]
      - ["pull_request_comment"]
      - ["pull_request_review"]
      - ["pull_request_review_comment"]
      - ["pull_request"]
      - ["pull_request_target"]
      - ["workflow_run"] # depending on branch filter
      - ["workflow_call"] # depending on caller
      - ["workflow_dispatch"] 
      - ["scheduled"]
```

However, when we drill down into `actions/ql/lib/codeql/actions/security/UntrustedCheckoutQuery.qll`, we see:

```
string checkoutTriggers() {
  result = ["pull_request_target", "workflow_run", "workflow_call", "issue_comment"]
}
```

This means that the unstrusted checkout property (which is required to get a checkout TOCTOU) will never apply unless the trigger is one of the above.
