### ISSUE TITLE
can't change jdk for maven when build on lgtm.com

### ISSUE THREAD

**Issue by hieplq** [github/codeql#3900]
[build log](https://lgtm.com/logs/bceba5d909c9f77ad5ab9b988ba2e3197b71e55f/lang:java)

i try to build my project with bellow test configuration. i already set java to 11 but maven still use jdk8

```
extraction:
  java:
    after_prepare: "export PATH=$LGTM_WORKSPACE/tools:$PATH"
    index:
      maven:
        version: "3.5.2"
        settings_file: "/opt/share/settings.xml"
        toolchains_file: "/opt/share/toolchains.xml"
      gradle:
        version: "4.4"
      build_command: "mvn verify -X -e"
      xml_mode: "default"
      java_version: "11"
      properties_files: true
```
