### ISSUE TITLE
CodeQL warning on pull requests for Jan 2021

### ISSUE THREAD

**Issue by vadi2** [github/codeql#4850]
I've setup my CodeQL to only run on commits merged to `development`, and not on each PR, because it takes too long. This is my setup:

```
on:
  push:
    branches: [development, main]
  schedule:
    - cron: '0 7 * * 3'
```

However, I get this warning:

>  2 issues were detected with this workflow: Please make sure that every branch in on.pull_request is also in on.push so that Code Scanning can compare pull requests against the state of the base branch. Please specify an on.pull_request hook so that Code Scanning is explicitly run against pull requests. This will be required to see results on pull requests from January 31 2021. 

If I don't want to see results from pull requests, is this warning still applicable?
