### ISSUE TITLE
Branch not found: "master" on LGTM

### ISSUE THREAD

**Issue by TheDGOfficial** [github/codeql#5149]
**Description of the issue**

I have a new GitHub repository with Maven and Java code. It builds successfully on my computer, GitHub Actions, CodeQL, Renovate/Dependabot, etc. all working.

But the LGTM build fails with the error branch not found “master”. I think it is because by main branch name is “main” (the new GitHub default, and since my repository is a new one, it used that while creating)

Why it can’t detect my main branch name? (Please do not suggest changing from main to master)

Also. is CodeQL checks for all LGTM checks, too? I was using LGTM before. CodeQL seems like it only checks security issues? Right? Wrong? Please correct me. If it checks all checks on LGTM then I might just not use LGTM, because CodeQL works right in GitHub Actions for me.

Screenshot:
![image](https://user-images.githubusercontent.com/24778409/107691258-460f6e80-6cbc-11eb-9bc8-6b3cf364dfb1.png)

It says “UserError” though I did not set anything about Git or branch name in LGTM. This my LGTM config (.lgtm.yml in root):

```yml
queries:
    -   include: "*"
extraction:
    java:
        index:
            build_command:
                - mvn clean verify -T 1C
```
