### ISSUE TITLE
LGTM.com - Linux distribution?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [github/codeql#6447]
**Description of the issue**

You need to document the underlying Linux distribution so that we can guess the name of the packages to install in `lgtm.yml`. For example:
```
extraction:
  cpp:
    prepare:
      packages: "vpnc-scripts"
```
The name of the package is `vpnc-scripts`on Debian or Ubuntu and `vpnc-script` on Fedora.
