### ISSUE TITLE
How to disable particular rule by its ID from GitHub workflow?

### ISSUE THREAD

**Issue by sungam3r** [github/codeql#7937]
Sorry but I did not find the answer in docs. For example, I want to disable `cs/linq/missed-where`.

**Comment by aeisenberg** [comment]
There is no simple way to do this. You could create a custom query suite. In your workflow's codeql init step, you would specify a config file to use:

```yml
- uses: github/codeql-action/init@v1
  with:
    config-file: ./.github/codeql/codeql-config.yml
```

And then in the config file, you [specify custom queries](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#specifying-additional-queries):

```yml
disable-default-queries: true
queries:
  - uses: ./github/codeql/suite.qls
```

And finally, you need to [create the query suite](https://codeql.github.com/docs/codeql-cli/creating-codeql-query-suites/) itself:

```yml
- from: codeql/csharp-queries
  apply: codeql-suites/csharp-security-and-quality.qls
- exclude:
    query filename: MissedWhereOpportunity.ql
```

Using this, you will have control over exactly which queries you want to run.
